# -*- coding: utf-8 -*-
"""DIVI_MLWA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14n7xN4AeNbELd2hqLzdB99XOehGl7caC
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.cluster import KMeans

# ==============================================================================
# 1. 修正後的模型 (Diagnosable Variational GMM)
# ==============================================================================
class DiagnosableGMM(nn.Module):
    def __init__(self, input_dim, num_components, prior_phi_probs,
                init_means=None, temperature=1.0, beta_mult=1.0):
        super().__init__()
        self.D = input_dim
        self.K = num_components
        self.temperature = temperature
        # MLWA
        self.beta_mult = beta_mult

        # Buffer
        self.register_buffer('prior_phi_probs', prior_phi_probs)
        # Fix 3: 背景分佈設寬一點 (Variance=5.0 -> LogVar=1.6)
        # 這樣數據只要稍微聚集，就會比背景更有吸引力
        self.register_buffer('prior_mu_0', torch.zeros(input_dim))
        # self.register_buffer('prior_logvar_0', torch.tensor([1.6] * input_dim))
        self.register_buffer('prior_logvar_0', torch.tensor([2.197] * input_dim))
        # --- Variational Parameters ---

        # Fix 2: Phi 初始化直接繼承 Step A 的 Prior (Inverse Sigmoid)
        # 這樣模型一開始就會"相信" Step A 的判斷
        prior_logits = torch.log(prior_phi_probs / (1 - prior_phi_probs))
        self.phi_logits = nn.Parameter(prior_logits.clone())

        # Fix 1: Mu 初始化 (如果有的話)
        if init_means is not None:
            # 確保維度匹配 [K, D]
            if init_means.shape[0] < num_components:
                # 如果分裂了，補隨機
                pad = torch.randn(num_components - init_means.shape[0], input_dim)
                init_means = torch.cat([init_means, pad], dim=0)
            self.q_mu = nn.Parameter(init_means)
        else:
            self.q_mu = nn.Parameter(torch.randn(num_components, input_dim))

        # LogVar 初始化小一點 (std=0.5 -> logvar=-1.38)，讓 Cluster 比較尖銳
        self.q_logvar = nn.Parameter(torch.ones(num_components, input_dim) * -1.0)
        self.pi_logits = nn.Parameter(torch.ones(num_components))

    def gumbel_sigmoid_sample(self, logits):
        uniform = torch.rand_like(logits)
        gumbel = -torch.log(-torch.log(uniform + 1e-9) + 1e-9)
        return torch.sigmoid((logits + gumbel) / self.temperature)

    def forward(self, X):
        N, D = X.shape
        phi_sample = self.gumbel_sigmoid_sample(self.phi_logits).unsqueeze(0)

        x_exp = X.unsqueeze(1)
        mu_exp = self.q_mu.unsqueeze(0)
        logvar_exp = self.q_logvar.unsqueeze(0)

        log_prob_cluster = -0.5 * (np.log(2 * np.pi) + logvar_exp + (x_exp - mu_exp)**2 / torch.exp(logvar_exp))
        log_prob_bg = -0.5 * (np.log(2 * np.pi) + self.prior_logvar_0 + (x_exp - self.prior_mu_0)**2 / torch.exp(self.prior_logvar_0))

        weighted_log_prob = phi_sample.unsqueeze(1) * log_prob_cluster + \
                            (1 - phi_sample.unsqueeze(1)) * log_prob_bg

        log_p_x_given_z = weighted_log_prob.sum(dim=2)

        pi = torch.softmax(self.pi_logits, dim=0)
        log_joint = log_p_x_given_z + torch.log(pi + 1e-9).unsqueeze(0)
        log_likelihood = torch.logsumexp(log_joint, dim=1).sum()

        q_phi = torch.sigmoid(self.phi_logits)
        q_phi = torch.clamp(q_phi, 1e-6, 1-1e-6)
        p_phi = torch.clamp(self.prior_phi_probs, 1e-6, 1-1e-6)

        # kl_phi = (q_phi * (torch.log(q_phi) - torch.log(p_phi)) + \
        #          (1 - q_phi) * (torch.log(1 - q_phi) - torch.log(1 - p_phi))).sum() * N
        # MLWA
        kl_raw = (q_phi * (torch.log(q_phi) - torch.log(p_phi)) + \
                (1 - q_phi) * (torch.log(1 - q_phi) - torch.log(1 - p_phi))).sum()

        kl_phi = self.beta_mult * N * kl_raw

        loss = -log_likelihood + kl_phi
        return loss, q_phi, log_p_x_given_z

    def get_cluster_diagnostics(self, X):
        with torch.no_grad():
            _, _, log_p_x_given_z = self.forward(X)
            z_hard = torch.argmax(log_p_x_given_z, dim=1)
            cluster_scores = []

            for k in range(self.K):
                mask = (z_hard == k)
                if mask.sum() == 0:
                    cluster_scores.append(0.0)
                else:
                    log_probs = log_p_x_given_z[mask, k]
                    score = -log_probs.mean().item()
                    cluster_scores.append(score)
            return np.array(cluster_scores)

# ==============================================================================
# 2. 修正後的 Wrapper Class
# ==============================================================================
class DIVIClustering:


    def __init__(self,
                split_threshold=22.0,
                split_interval=60,
                max_epochs=300,
                lr=0.05,
                max_components=None,
                # MLWA
                beta_mult=1.0,
                rough_k=3,
                verbose=True):
        self.split_threshold = split_threshold
        self.split_interval = split_interval
        self.max_epochs = max_epochs
        self.lr = lr
        self.max_components = max_components
        # MLWA
        self.beta_mult = beta_mult
        self.rough_k = rough_k
        self.verbose = verbose

        self.model = None
        self.history = {'loss': [], 'k': [], 'phi': []}


    def _step_a_calculate_prior(self, X, mode=1, w_kw=1.0, w_llr=1.0):
        """
        執行數據啟發式先驗計算。
        mode=1: Informative (KW Test + LLR)
        mode=2: Non-informative (0.5)
        mode=3: Random Prior
        """
        N, D = X.shape

        if mode == 1:
            if self.verbose: print("   -> Mode 1: Computing Combined KW & LLR scores...")

            # 預分群：使用自適應 K
            # k_rough = min(3, N)
            k_rough = min(self.rough_k, N)
            kmeans = KMeans(n_clusters=k_rough, random_state=42).fit(X)
            labels = kmeans.labels_

            final_scores = []
            for j in range(D):
                feat = X[:, j]
                groups = [feat[labels == k] for k in range(k_rough) if len(feat[labels == k]) > 0]

                # --- (A) Kruskal-Wallis 統計量 ---
                kw_stat = 0
                if len(groups) > 1:
                    try:
                        stat, _ = stats.kruskal(*groups)
                        kw_stat = np.log1p(stat)
                    except: kw_stat = 0

                # --- (B) LLR (Log-Likelihood Ratio) 近似 ---
                # H0: 全域高斯 (Global Gaussian)
                var_0 = np.var(feat) + 1e-6
                ll_0 = -0.5 * np.sum((feat - np.mean(feat))**2) / var_0 - N * 0.5 * np.log(var_0)

                # H1: 分群高斯 (Clustered Gaussian)
                ll_1 = 0
                for group in groups:
                    if len(group) > 1:
                        v_k = np.var(group) + 1e-6
                        ll_1 += -0.5 * np.sum((group - np.mean(group))**2) / v_k - len(group) * 0.5 * np.log(v_k)

                llr_stat = max(0, ll_1 - ll_0)
                llr_stat = np.log1p(llr_stat) # 壓縮極端值

                # 結合分數
                final_scores.append(w_kw * kw_stat + w_llr * llr_stat)

            # 歸一化與轉換
            final_scores = np.array(final_scores)
            norm = (final_scores - final_scores.min()) / (final_scores.max() - final_scores.min() + 1e-9)

            # 使用 scale=6 增強區分度，並加上 clamp 確保數值穩定
            logits = (norm - 0.5) * 6
            rho = torch.sigmoid(torch.tensor(logits, dtype=torch.float32))
            rho = torch.clamp(rho, 0.01, 0.99) # 關鍵：防止梯度消失或 NaN

        elif mode == 2:
            rho = torch.full((D,), 0.5, dtype=torch.float32)
        elif mode == 3:
            rho = torch.rand(D, dtype=torch.float32)

        return rho


    def _expand_model(self, old_model, split_idx):
        D, K = old_model.D, old_model.K

        # 建立新模型 (繼承 Prior)
        # new_model = DiagnosableGMM(D, K + 1, old_model.prior_phi_probs, temperature=old_model.temperature)
        # MLWA
        new_model = DiagnosableGMM(
            D, K + 1,
            old_model.prior_phi_probs,
            temperature=old_model.temperature,
            beta_mult=old_model.beta_mult
        )

        # 1. 繼承 Phi (關鍵！不要重置)
        with torch.no_grad():
            new_model.phi_logits.copy_(old_model.phi_logits)

            # 2. 繼承 Mu
            old_mu = old_model.q_mu.data
            target_mu = old_mu[split_idx]
            mu_a = target_mu + torch.randn(D) * 0.2 # 縮小擾動
            mu_b = target_mu - torch.randn(D) * 0.2

            keep_idx = [i for i in range(K) if i != split_idx]
            if keep_idx:
                new_mus = torch.cat([old_mu[keep_idx], mu_a.unsqueeze(0), mu_b.unsqueeze(0)], dim=0)
            else:
                new_mus = torch.cat([mu_a.unsqueeze(0), mu_b.unsqueeze(0)], dim=0)
            new_model.q_mu.copy_(new_mus)

            # 3. 繼承 LogVar (保持寬度)
            old_logvar = old_model.q_logvar.data
            target_logvar = old_logvar[split_idx]
            if keep_idx:
                new_logvars = torch.cat([old_logvar[keep_idx], target_logvar.unsqueeze(0), target_logvar.unsqueeze(0)], dim=0)
            else:
                new_logvars = torch.cat([target_logvar.unsqueeze(0), target_logvar.unsqueeze(0)], dim=0)
            new_model.q_logvar.copy_(new_logvars)

        return new_model
    import numpy as np

    def fit(self, X_np, use_prior=1):
        X_tensor = torch.tensor(X_np, dtype=torch.float32)
        N, D = X_tensor.shape

        # === 自動設定閾值 ===
        # 0.8 是一個經驗法則，代表我們期望 Cluster 的緊密度是整體的 80%
        if self.split_threshold is None:
            # $$H \approx \frac{D}{2} (1 + \ln(2\pi) + \ln(\sigma^2))$$
            self.split_threshold = 0.5 * D * (1 + np.log(2 * np.pi) + np.log(1.0))
            if self.verbose:
                print(f"Auto-configured Split Threshold: {self.split_threshold:.2f} (based on D={D}, tightness=0.8)")


        # 1. Step A 帶入 mode
        rho = self._step_a_calculate_prior(X_np, mode=use_prior)

        # 2. 初始化 K=1 (Fix 1: 使用全局均值初始化 Mu)
        global_mean = torch.mean(X_tensor, dim=0, keepdim=True) # [1, D]
        # self.model = DiagnosableGMM(D, 1, rho, init_means=global_mean)
        # MLWA
        self.model = DiagnosableGMM(D, 1, rho, init_means=global_mean, beta_mult=self.beta_mult)
        optimizer = optim.Adam(self.model.parameters(), lr=self.lr)

        if self.verbose: print(f"Starting Training (Initial K=1)...")

        for epoch in range(1, self.max_epochs + 1):
            self.model.train()
            optimizer.zero_grad()
            loss, q_phi, _ = self.model(X_tensor)
            loss.backward()
            optimizer.step()

            self.model.temperature = max(0.1, self.model.temperature * 0.98)

            self.history['loss'].append(loss.item())
            self.history['k'].append(self.model.K)
            self.history['phi'].append(q_phi.detach().numpy())

            if epoch % self.split_interval == 0:
                scores = self.model.get_cluster_diagnostics(X_tensor)
                worst_idx = np.argmax(scores)
                worst_score = scores[worst_idx]

                if self.verbose:
                    # 顯示當前狀態
                    phi_curr = q_phi.detach().numpy()
                    print(f"Epoch {epoch}: K={self.model.K}, Max NLL={worst_score:.2f}")
                    # print(f"   Phi[0]={phi_curr[0]:.2f}, Phi[9]={phi_curr[9]:.2f}")

                # MLWA
                can_split = (self.max_components is None) or (self.model.K < self.max_components)

                if (worst_score > self.split_threshold) and can_split:
                    if self.verbose: print(f"   >>> Splitting Cluster {worst_idx}...")
                    self.model = self._expand_model(self.model, worst_idx)
                    optimizer = optim.Adam(self.model.parameters(), lr=self.lr)
                elif (worst_score > self.split_threshold) and (not can_split):
                    if self.verbose:
                        print(f"   >>> Split blocked: K reached max_components={self.max_components}")
                # if worst_score > self.split_threshold:
                #     if self.verbose: print(f"   >>> Splitting Cluster {worst_idx}...")
                #     self.model = self._expand_model(self.model, worst_idx)
                #     optimizer = optim.Adam(self.model.parameters(), lr=self.lr)

        if self.verbose: print("Training Completed.")
        return self